# vim:tw=0:ts=4:sw=4:et:norl
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/doblabs/python-editor-hotoffthehamster
# License: MIT

EAPP_MAKEFILE_PYDOCSTYLE_DISABLE ?= true

# FIXME/2023-12-27: Repair Windows CI tests. See comment in test_editor.py
EAPP_MAKEFILE_TESTS_WINDOWS_DISABLE ?= true

